spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mechDB
    username: postgres
    password: levi3108
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      show-sql: false
        
